services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./Wordpress:/var/www/html
    links:
      - db
  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1305Kel@
      MYSQL_USER: Keltton
      MYSQL_PASSWORD: 1305Kel@
      MYSQL_DATABASE: Wordpress
  phpmyadmin:
    image: phpmyadmin
    links:
      - ./db:db
    restart: always
    ports:
      - 5005:80
    environment:
      - MYSQL_ROOT_PASSWORD:1305Kel@
